### ISSUE TITLE
complete the matrix of distro like below

### ISSUE THREAD

**Issue by sgaunet** [sgaunet/ansible-role-restic#1]
```
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux9
          - rockylinux8
          - ubuntu2204
          - ubuntu2004
          - debian12
          - debian11
          - debian10
          - fedora39
```
